### ISSUE TITLE
Failing test on fresh install - ruby 2.3.4p301 - using rake command

### ISSUE THREAD

**Issue by Mirv** [iCodeSometime/asynchronize#3]
mirv:~/workspace (master) $ rake
Run options: --seed 8370

# Running:

.......E

Error:
Asynchronize::when there is an existing method_added#test_0001_should call that method_added before, and only once.:
NoMethodError: private method `undef_method' called for #<Class:BasicSpec::MethodAddedTest>
    /home/ubuntu/workspace/lib/asynchronize.rb:37:in `block in included'
    /home/ubuntu/workspace/lib/asynchronize.rb:4:in `class_eval'
    /home/ubuntu/workspace/lib/asynchronize.rb:4:in `included'
    /home/ubuntu/workspace/spec/spec.rb:125:in `include'
    /home/ubuntu/workspace/spec/spec.rb:125:in `<class:MethodAddedTest>'
    /home/ubuntu/workspace/spec/spec.rb:113:in `block (3 levels) in <class:BasicSpec>'

bin/rails test home/ubuntu/workspace/spec/spec.rb:132

......

Finished in 0.010901s, 1284.2483 runs/s, 1284.2483 assertions/s.
14 runs, 14 assertions, 0 failures, 1 errors, 0 skips

COVERAGE: 100.00% -- 36/36 lines in 1 files

rake aborted!
Command failed with status (1)
/usr/local/rvm/gems/ruby-2.3.4/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
mirv:~/workspace (master) $ ruby -v
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
mirv:~/workspace (master) $ rails -v
Rails 5.2.0
mirv:~/workspace (master) $

**Comment by iCodeSometime** [comment]
Installing that version to try to reproduce

**Comment by iCodeSometime** [comment]
Looks like a method visibility error. Try with the latest commit please.

**Comment by iCodeSometime** [comment]
I guess undef_method used to be private in older versions of ruby. I've added Ruby 2.2.2 as a version to test in travis, since it's the oldest I've been able to verify with so far. I plan on verifying other versions as I'm able

**Comment by iCodeSometime** [comment]
You told me in chat this is working since the latest commit

**Comment by Mirv** [comment]
Correct yes - the latest pull seemed to have alleviated this issue!
